### ISSUE TITLE
ImportError: cannot import name core

### ISSUE THREAD

**Issue by smazcw3** [PrincetonUniversity/DP_GP_cluster#13]
While running the test on Mac with python 2.7 
DP_GP_cluster.py -i test/test.txt -o test/test -p png -n 20 --plot

I am getting the following error

```
    from DP_GP import core
ImportError: cannot import name core
```

Can you provide some assistance to fix this?

**Comment by smazcw3** [comment]
solved this problem by myself.

**Comment by tanishq67** [comment]
Coule you please let me know, how you was able to solve the issue
