### ISSUE TITLE
How does Replicates being Treated in this Program

### ISSUE THREAD

**Issue by yueyaog** [PrincetonUniversity/DP_GP_cluster#18]
Hi devs,

I have been executing the code with our RNA-Seq time-series results with three replicates. It produced a pretty promising clustering results for me. Before moving forward with my results, I would love to know how does the replicates being treated in the program. 

Thanks,
Gao

**Comment by StefDiV** [comment]
Hi! Did you find out about the replicates? I have a similar situation and would like to know better how are the replicates processed

**Comment by zkstewart** [comment]
Likewise, I was interested in trying this program but am unsure how I should be handling biological replicates. By all appearances it looks like I should be getting the average count across replicates, but I'd rather use an algorithm that uses the replicates to improve the statistical strength of any results.

**Comment by yueyaog** [comment]
In DP GP, the replicates were compressed into an average value. However, you could use each individual replicate as its own entry to avoid the averaging problem. Regarding the averaging issue, I've created a temporal differential analysis workflow for RNA-Seq data that treats each biological replicate as an independent pattern in the analysis.
 Here is the link to the workflow repo: https://github.com/yueyaog/GeneShift. You can find more details about it in this publication: https://www.frontiersin.org/articles/10.3389/fpls.2022.861639/full.
