### ISSUE TITLE
Plot data after getting results

### ISSUE THREAD

**Issue by ngaitan55** [PrincetonUniversity/DP_GP_cluster#27]
Hello!
I want to know how can i generate the cluster expression levels, cluster size progression and the posterior matrix dendrogram graphics after getting the results, using the .txt result files as input. The thing is i ran dpgp on a high performance cluster but it did not generate the graphics that i get when running it on my pc, and it would be difficult for me tu run it again. Thank you and i am looking forward to your input on this topic.

**Comment by IanMcDowell** [comment]
Check out bin/DP_GP_cluster_post_gibbs_sampling.py, the usage is pretty well described, so you should be able to figure it out.
