### ISSUE TITLE
Unable to install and test DP_GP

### ISSUE THREAD

**Issue by kanekalla** [PrincetonUniversity/DP_GP_cluster#4]
Hello team,

I am trying to use DP_GP but having difficult to use it.
The recent error that I got is after trying to install
python2.7 setup.py install
Traceback (most recent call last):
  File "setup.py", line 2, in <module>
    from Cython.Distutils import build_ext 
ImportError: No module named Cython.Distutils

I also tried to run the test plot directly from the bin
 python2.7 bin/DP_GP_cluster.py -i test/test.txt -o test/test -p png -n 20 --plot
Traceback (most recent call last):
  File "bin/DP_GP_cluster.py", line 24, in <module>
    from DP_GP import plot
ImportError: No module named DP_GP

Can you kindly look into this?

**Comment by IanMcDowell** [comment]
Please install cython and retry. Let me know the error message

On Wed, Feb 28, 2018 at 8:15 PM, Kishore R. Anekalla <
notifications@github.com> wrote:

> Hello team,
>
> I am trying to use DP_GP but having difficult to use it.
> The recent error that I got is after trying to install
> python2.7 setup.py install
> Traceback (most recent call last):
> File "setup.py", line 2, in
> from Cython.Distutils import build_ext
> ImportError: No module named Cython.Distutils
>
> I also tried to run the test plot directly from the bin
> python2.7 bin/DP_GP_cluster.py -i test/test.txt -o test/test -p png -n 20
> --plot
> Traceback (most recent call last):
> File "bin/DP_GP_cluster.py", line 24, in
> from DP_GP import plot
> ImportError: No module named DP_GP
>
> Can you kindly look into this?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_PrincetonUniversity_DP-5FGP-5Fcluster_issues_4&d=DwMCaQ&c=imBPVzF25OnBgGmVOlcsiEgHoG1i6YHLR0Sj_gZ4adc&r=QGd0b_06v3hDpkoxZUB9c2iQ5RMTOts_DJ98uEZzA-o&m=wdNCJHRpr1z-zCxmsBt2Zd-byi3zW2fhKpXLBSaANeo&s=XohbACExOc1dOKb-Ro7PF0R96IYUMZ5v6Sg59iV5tOM&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AFnc9DzGVS-2D9pKe83k7FZhuBHSrZ9900ks5tZ0uXgaJpZM4SXnCG&d=DwMCaQ&c=imBPVzF25OnBgGmVOlcsiEgHoG1i6YHLR0Sj_gZ4adc&r=QGd0b_06v3hDpkoxZUB9c2iQ5RMTOts_DJ98uEZzA-o&m=wdNCJHRpr1z-zCxmsBt2Zd-byi3zW2fhKpXLBSaANeo&s=fqY4omb-a89WMPY_PXlCHIrhnn1C3HTriljEwCAEG7s&e=>
> .
>



-- 
Ian McDowell
Bioinformatician II
Duke University

**Comment by kanekalla** [comment]
Hi Ian,

installed successfully and I am getting scipy.cluster.hierarchy error.
Installing output:
running install
running build
running build_py
running build_ext
skipping 'DP_GP/core.c' Cython extension (up-to-date)
skipping 'DP_GP/cluster_tools.c' Cython extension (up-to-date)
running build_scripts
running install_lib
running install_scripts
changing mode of /home/kishore/.virtualenvs/iso/bin/DP_GP_cluster.py to 775
running install_egg_info
Removing /home/kishore/.virtualenvs/iso/lib/python2.7/site-packages/DP_GP_cluster-0.1-py2.7.egg-info
Writing /home/kishore/.virtualenvs/iso/lib/python2.7/site-packages/DP_GP_cluster-0.1-py2.7.egg-info



Error: 
Traceback (most recent call last):
  File "/usr/local/bin/DP_GP_cluster.py", line 24, in <module>
    from DP_GP import plot
  File "/usr/local/lib/python2.7/dist-packages/DP_GP/plot.py", line 11, in <module>
    from scipy.cluster.hierarchy import linkage, dendrogram
ImportError: No module named scipy.cluster.hierarchy

However, I am able to load scipy.cluster.heirarchy using python CLI
Python 2.7.14 (default, Sep 23 2017, 22:06:14) 
[GCC 7.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import scipy.cluster.hierarchy
>>>

**Comment by IanMcDowell** [comment]
DPGP has the following requirements:

GPy, pandas, numpy, scipy (>= 0.14), matplotlib.pyplot

Install and retry please.

On Thu, Mar 1, 2018 at 11:09 PM, Kishore R. Anekalla <
notifications@github.com> wrote:

> Hi Ian,
>
> installed successfully and I am getting scipy.cluster.hierarchy error.
> Installing output:
> running install
> running build
> running build_py
> running build_ext
> skipping 'DP_GP/core.c' Cython extension (up-to-date)
> skipping 'DP_GP/cluster_tools.c' Cython extension (up-to-date)
> running build_scripts
> running install_lib
> running install_scripts
> changing mode of /home/kishore/.virtualenvs/iso/bin/DP_GP_cluster.py to
> 775
> running install_egg_info
> Removing /home/kishore/.virtualenvs/iso/lib/python2.7/site-
> packages/DP_GP_cluster-0.1-py2.7.egg-info
> Writing /home/kishore/.virtualenvs/iso/lib/python2.7/site-
> packages/DP_GP_cluster-0.1-py2.7.egg-info
>
> Error:
> Traceback (most recent call last):
> File "/usr/local/bin/DP_GP_cluster.py", line 24, in
> from DP_GP import plot
> File "/usr/local/lib/python2.7/dist-packages/DP_GP/plot.py", line 11, in
> from scipy.cluster.hierarchy import linkage, dendrogram
> ImportError: No module named scipy.cluster.hierarchy
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_PrincetonUniversity_DP-5FGP-5Fcluster_issues_4-23issuecomment-2D369814511&d=DwMFaQ&c=imBPVzF25OnBgGmVOlcsiEgHoG1i6YHLR0Sj_gZ4adc&r=QGd0b_06v3hDpkoxZUB9c2iQ5RMTOts_DJ98uEZzA-o&m=Foz340mOxSZgftpfk93tPpFXC21gFsZE3M_BskOOvdA&s=k23wA8JNV7vGyr_SxDmM8ol7B1GEsNw4-nIfnDizWdQ&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AFnc9CoYlHEtzGt2qbGCXgQncL9wFPKiks5taMYBgaJpZM4SXnCG&d=DwMFaQ&c=imBPVzF25OnBgGmVOlcsiEgHoG1i6YHLR0Sj_gZ4adc&r=QGd0b_06v3hDpkoxZUB9c2iQ5RMTOts_DJ98uEZzA-o&m=Foz340mOxSZgftpfk93tPpFXC21gFsZE3M_BskOOvdA&s=Ja2bpweE6t2aVPmYOO5DZvorH-jkAKZD1tvrkt-vRxo&e=>
> .
>



-- 
Ian McDowell
Bioinformatician II
Duke University

**Comment by kanekalla** [comment]
Hello Ian, 
I am still unable to test DP_GP.

I have cross checked the versions,

Python 2.7.14 (default, Sep 23 2017, 22:06:14) 
[GCC 7.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import GPy
>>> import matplotlib
>>> import pandas
>>> import numpy
>>> import scipy
>>> print scipy.__version__
1.0.0
>>> print numpy.__version__
1.14.1
>>> print GPy.__version__
1.9.2
>>> print pandas.__version__
0.22.0
>>> print matplotlib.__version__
2.1.2
>>> import matplotlib.pyplot
>>> print sklearn.__version__
0.19.1


**Error:**
(iso) kishore@Jaya:~winter1718/rotation/DP_GP_cluster$ DP_GP_cluster.py -i test/test.txt -o test/test -p png -n 20 --plot
Traceback (most recent call last):
  File "/home/kishore/.virtualenvs/iso/bin/DP_GP_cluster.py", line 24, in <module>
    from DP_GP import plot
  File "/usr/local/lib/python2.7/dist-packages/DP_GP/plot.py", line 11, in <module>
    from scipy.cluster.hierarchy import linkage, dendrogram
ImportError: No module named scipy.cluster.hierarchy

I am running using virtual environment created using virtualenvwrapper.

**Comment by IanMcDowell** [comment]
Hmm, that's strange. Try running for yourself:

from scipy.cluster.hierarchy import linkage, dendrogram

If that works, then DPGP is finding a different python than your usual
python path.

On Fri, Mar 2, 2018 at 11:02 AM, Kishore R. Anekalla <
notifications@github.com> wrote:

> Hello Ian,
> I am still unable to test DP_GP.
>
> I have cross checked the versions,
>
> Python 2.7.14 (default, Sep 23 2017, 22:06:14)
> [GCC 7.2.0] on linux2
> Type "help", "copyright", "credits" or "license" for more information.
>
> import GPy
> import matplotlib
> import pandas
> import numpy
> import scipy
> print scipy.*version*
> 1.0.0
> print numpy.*version*
> 1.14.1
> print GPy.*version*
> 1.9.2
> print pandas.*version*
> 0.22.0
> print matplotlib.*version*
> 2.1.2
> import matplotlib.pyplot
>
> *Error:*
> (iso) kishore@Jaya:~winter1718/rotation/DP_GP_cluster$ DP_GP_cluster.py
> -i test/test.txt -o test/test -p png -n 20 --plot
> Traceback (most recent call last):
> File "/home/kishore/.virtualenvs/iso/bin/DP_GP_cluster.py", line 24, in
> from DP_GP import plot
> File "/usr/local/lib/python2.7/dist-packages/DP_GP/plot.py", line 11, in
> from scipy.cluster.hierarchy import linkage, dendrogram
> ImportError: No module named scipy.cluster.hierarchy
>
> I am running using virtual environment created using virtualenvwrapper.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_PrincetonUniversity_DP-5FGP-5Fcluster_issues_4-23issuecomment-2D369963993&d=DwMFaQ&c=imBPVzF25OnBgGmVOlcsiEgHoG1i6YHLR0Sj_gZ4adc&r=QGd0b_06v3hDpkoxZUB9c2iQ5RMTOts_DJ98uEZzA-o&m=bXYT9PRY1_rj7nwprA_SLG1xffAgUbWDCfRT9ifzHTc&s=m_vj5fNkhoa3d7gC4upFgiVIqiM667JDJ27-TDbhegA&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AFnc9NSetQouBZhbgqWWe6eg4x7zyiNnks5taW0OgaJpZM4SXnCG&d=DwMFaQ&c=imBPVzF25OnBgGmVOlcsiEgHoG1i6YHLR0Sj_gZ4adc&r=QGd0b_06v3hDpkoxZUB9c2iQ5RMTOts_DJ98uEZzA-o&m=bXYT9PRY1_rj7nwprA_SLG1xffAgUbWDCfRT9ifzHTc&s=oH6ClqQSLmzL7Fqa9ttdkuSxZ6gjiH68n9fIiGGgEt8&e=>
> .
>



-- 
Ian McDowell
Bioinformatician II
Duke University

**Comment by kanekalla** [comment]
Python 2.7.14 (default, Sep 23 2017, 22:06:14) 
[GCC 7.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from scipy.cluster.hierarchy import linkage, dendrogram
>>> 

This one seems working

**Comment by kanekalla** [comment]
Hi Ian,

I opted out of virtual environment and running directly and its running now.
It might be because of virtual environment its taking different path.

Thanks for your help !!
