### ISSUE TITLE
NameError: name 'sim_mat_key' is not defined

### ISSUE THREAD

**Issue by jcharalel** [PrincetonUniversity/DP_GP_cluster#6]
Hi Ian,

Thanks for creating this package!  I was able to install and run the test example on my Mac but when I tried on our cluster, installation seemed to proceed ok but when I try the test command: 

DP_GP_cluster.py -i test/test.txt -o test/test -p png -n 20 --plot

I get the following error and, no plots are generated.  Do you have an idea on to how to fix this?

Optimizing parameters for optimal clusters.
Cluster 1, 20 genes
Cluster 2, 20 genes
Cluster 3, 20 genes
Cluster 4, 20 genes
Cluster 5, 20 genes
Cluster 6, 20 genes
Saving sampling results.
Plotting expression and sampling results.
WARNING: skipping heatmap plot generation, too many dendrogram recursions for scipy to handle
Traceback (most recent call last):
  File "/srv/gsfs0/projects/curtis/jcharalel/dev/packages/anaconda/envs/dpgp/bin/DP_GP_cluster.py", line 683, in <module>
    core.save_posterior_similarity_matrix_key([gene_names[idx] for idx in sim_mat_key], args.output_path_prefix)
NameError: name 'sim_mat_key' is not defined

Looking back at the installation of the dependency GPy, I did receive error messages but it looked like it salvaged.  I'm including it here in case its informative:
Collecting GPy
  Using cached GPy-1.9.2.tar.gz
Requirement already satisfied: numpy>=1.7 in /home/jcharale/miniconda3/envs/dpgp_mini/lib/python2.7/site-packages (from GPy)
Requirement already satisfied: scipy>=0.16 in /home/jcharale/miniconda3/envs/dpgp_mini/lib/python2.7/site-packages (from GPy)
Requirement already satisfied: six in /home/jcharale/miniconda3/envs/dpgp_mini/lib/python2.7/site-packages (from GPy)
Collecting paramz>=0.9.0 (from GPy)
  Using cached paramz-0.9.1.tar.gz
Collecting decorator>=4.0.10 (from paramz>=0.9.0->GPy)
  Using cached decorator-4.2.1-py2.py3-none-any.whl
Building wheels for collected packages: GPy, paramz
  Running setup.py bdist_wheel for GPy ... error
  Complete output from command /home/jcharale/miniconda3/envs/dpgp_mini/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-D7lSgG/GPy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpm3Ld83pip-wheel- --python-tag cp27:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: invalid command 'bdist_wheel'
  
  ----------------------------------------
  Failed building wheel for GPy
  Running setup.py clean for GPy
  Running setup.py bdist_wheel for paramz ... error
  Complete output from command /home/jcharale/miniconda3/envs/dpgp_mini/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-D7lSgG/paramz/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpYFM_GEpip-wheel- --python-tag cp27:
  usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: -c --help [cmd1 cmd2 ...]
     or: -c --help-commands
     or: -c cmd --help
  
  error: invalid command 'bdist_wheel'
  
  ----------------------------------------
  Failed building wheel for paramz
  Running setup.py clean for paramz
Failed to build GPy paramz
Installing collected packages: decorator, paramz, GPy
  Running setup.py install for paramz ... done
  Running setup.py install for GPy ... done
Successfully installed GPy-1.9.2 decorator-4.2.1 paramz-0.9.1

Thank you!

**Comment by IanMcDowell** [comment]
Sorry for the delay, what is your version of scipy? This hasn't been tested
on the new scipy 1.0. That could be it.

On Mon, Mar 12, 2018 at 7:10 PM, jcharalel <notifications@github.com> wrote:

> Hi Ian,
>
> Thanks for creating this package! I was able to install and run the test
> example on my Mac but when I tried on our cluster, installation seemed to
> proceed ok but when I try the test command:
>
> DP_GP_cluster.py -i test/test.txt -o test/test -p png -n 20 --plot
>
> I get the following error:
> Optimizing parameters for optimal clusters.
> Cluster 1, 20 genes
> Cluster 2, 20 genes
> Cluster 3, 20 genes
> Cluster 4, 20 genes
> Cluster 5, 20 genes
> Cluster 6, 20 genes
> Saving sampling results.
> Plotting expression and sampling results.
> WARNING: skipping heatmap plot generation, too many dendrogram recursions
> for scipy to handle
> Traceback (most recent call last):
> File "/srv/gsfs0/projects/curtis/jcharalel/dev/packages/
> anaconda/envs/dpgp/bin/DP_GP_cluster.py", line 683, in
> core.save_posterior_similarity_matrix_key([gene_names[idx] for idx in
> sim_mat_key], args.output_path_prefix)
> NameError: name 'sim_mat_key' is not defined
>
> And, no plots are generated. Do you have an idea on to how to fix this?
>
> Thank you!
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_PrincetonUniversity_DP-5FGP-5Fcluster_issues_6&d=DwMCaQ&c=imBPVzF25OnBgGmVOlcsiEgHoG1i6YHLR0Sj_gZ4adc&r=QGd0b_06v3hDpkoxZUB9c2iQ5RMTOts_DJ98uEZzA-o&m=GxAJzICBqmpJglr-nwZn7QIryYQlnABQdqmKBKRkZDU&s=0-wyrjlzZfJ2yzgBQiPa9xnVvXOwwfj5kZruYu6rVZQ&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AFnc9DM0GrzJnOTdizqxmKRjEVvyqQwXks5tdwBcgaJpZM4Sn1kb&d=DwMCaQ&c=imBPVzF25OnBgGmVOlcsiEgHoG1i6YHLR0Sj_gZ4adc&r=QGd0b_06v3hDpkoxZUB9c2iQ5RMTOts_DJ98uEZzA-o&m=GxAJzICBqmpJglr-nwZn7QIryYQlnABQdqmKBKRkZDU&s=pQgs9TB0j_ZZQ-lew_t1RNcnoUuG36aXBd25FcJJsXM&e=>
> .
>



-- 
Ian McDowell
Bioinformatician II
Duke University

**Comment by jcharalel** [comment]
Hey, no worries, I was able to get it resolved.  Turns out it was an issue with the display on the cluster.  Used a different backend and it worked.

**Comment by syl0125** [comment]
Hi @jcharalel , I also came across this issue. How did you solve it? Thanks!

**Comment by syl0125** [comment]
figure it out! if you run it on the cluster, you can add plt.switch_backend('agg') after import matplotlib.pyplot as plt.

**Comment by gurkanbebek** [comment]
The answer is not clear. I am having a similar issue. How do you go around this? I have scipy (1.1.0). Is that a problem?

**Comment by syl0125** [comment]
@gurkanbebek this issue is actually caused by matplotlib x11 backend, you can add  plt.switch_backend('agg') in the DP_GP_cluster.py script.

**Comment by gurkanbebek** [comment]
Thank you
