### ISSUE TITLE
Differences between fast and slow modes?

### ISSUE THREAD

**Issue by jcharalel** [PrincetonUniversity/DP_GP_cluster#7]
Hi Ian,

Thanks for building this tool! 

I was wondering if you could describe at a high level what the major differences are between the fast and slow modes?

Thank you!

**Comment by IanMcDowell** [comment]
At a high level, the fast mode uses a GP to models the mean expression of
each cluster, basically taking advantage of the fact that all genes are
sampled at the same times, collapsing profiles across genes. In the slow
mode the GP models the expression of all genes in a cluster simultaneously.

On Fri, Mar 16, 2018 at 8:28 PM, jcharalel <notifications@github.com> wrote:

> Hi Ian,
>
> Thanks for building this tool!
>
> I was wondering if you could describe at a high level what the major
> differences are between the fast and slow modes?
>
> Thank you!
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_PrincetonUniversity_DP-5FGP-5Fcluster_issues_7&d=DwMCaQ&c=imBPVzF25OnBgGmVOlcsiEgHoG1i6YHLR0Sj_gZ4adc&r=QGd0b_06v3hDpkoxZUB9c2iQ5RMTOts_DJ98uEZzA-o&m=9VCXu5pScEKaRqbAt8qIUnmxc5V1wpIQZSPThkF8cYc&s=_dTwRy9d7sqRuc1vcgFL1dZk2qlHQzPqjuXSV9MK2yU&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AFnc9EwTbCqQH6JqgUzlblmBIJTtaTh0ks5tfFiagaJpZM4SumA6&d=DwMCaQ&c=imBPVzF25OnBgGmVOlcsiEgHoG1i6YHLR0Sj_gZ4adc&r=QGd0b_06v3hDpkoxZUB9c2iQ5RMTOts_DJ98uEZzA-o&m=9VCXu5pScEKaRqbAt8qIUnmxc5V1wpIQZSPThkF8cYc&s=LmUe2BkQRB4kEmymsYUJKL11P-v_jMo8qOJWeLfDCt8&e=>
> .
>



-- 
Ian McDowell
Bioinformatician II
Duke University

**Comment by jcharalel** [comment]
Cool, thank you!
