### ISSUE TITLE
Recommendations on alpha

### ISSUE THREAD

**Issue by jcharalel** [PrincetonUniversity/DP_GP_cluster#8]
Hi Ian,

Do you have any recommendations on the alpha parameter?  I see that the default is 1 but I was wondering if you have thoughts on what a reasonable range is?  I have tried 0.25, 0.5, 1, 2, and considering going smaller as I feel like the cluster number would be better if further reduced (15-20 with the ones tried so far).

Thanks!

**Comment by IanMcDowell** [comment]
I have done little work testing various concentration parameters. In
practice, the number of clusters also strongly depends on a noise
hyperprior. The defaults worked well for me for RNA-seq data but I widened
the prior for microarray data, for example. I would recommend fixing
sigma_n shape or rate and systematically varying the other hyperparameter.

On Wed, Mar 21, 2018 at 7:42 PM, jcharalel <notifications@github.com> wrote:

> Hi Ian,
>
> Do you have any recommendations on the alpha parameter? I see that the
> default is 1 but I was wondering if you have thoughts on what a reasonable
> range is? I have tried 0.25, 0.5, 1, 2, and considering going smaller as I
> feel like the cluster number would be better if further reduced (15-20 with
> the ones tried so far).
>
> Thanks!
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_PrincetonUniversity_DP-5FGP-5Fcluster_issues_8&d=DwMCaQ&c=imBPVzF25OnBgGmVOlcsiEgHoG1i6YHLR0Sj_gZ4adc&r=QGd0b_06v3hDpkoxZUB9c2iQ5RMTOts_DJ98uEZzA-o&m=tLzn0sNky83Qy9ZvM9QZsYYk-INjvcF2tIjTVHBFtdg&s=zGgahedg_85BP4jRtB24eTzhMjbDVOY_a-XLFlulAbY&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AFnc9CCgN7O5YqXWU-2DLrvoO57sSSuO8Gks5tguVjgaJpZM4S2OpX&d=DwMCaQ&c=imBPVzF25OnBgGmVOlcsiEgHoG1i6YHLR0Sj_gZ4adc&r=QGd0b_06v3hDpkoxZUB9c2iQ5RMTOts_DJ98uEZzA-o&m=tLzn0sNky83Qy9ZvM9QZsYYk-INjvcF2tIjTVHBFtdg&s=lYlphrlG4yhqYn2DDvomQ4eA3tp0r9zHg2-YgXRpxDA&e=>
> .
>



-- 
Ian McDowell
Bioinformatician II
Duke University

**Comment by jcharalel** [comment]
Great thanks, I'll give that a shot!
